gpt-4-1106-preview: # only when using `model_name: gpt-4-1106-preview` which is AlpacaEval2's model name
    - "default" # this will append all the `default` configs

    - client_class: "openai.AzureOpenAI" # doesn't use the `openai.OpenAI` client class
      # the following are passed to the `AzureOpenAI` client class
      azure_deployment: "gpt-4-1106" # name of the latest GPT-4 turbo on azure change as needed
      azure_endpoint: "https://conversationhubswedencentral.openai.azure.com/"
      api_version: "2024-03-01-preview"
      identity_id: "18731b9d-0488-49be-bb05-6ccb08f78cf3"
